name: Adaptive Schedule Update

on:
  schedule:
    - cron: "31 1 * * *"
  workflow_dispatch:

jobs:
  update-schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT }}
      - uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync

      - name: Download data
        run: bash data/download.sh
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Calculate next cron schedule
        id: cron
        run: echo "schedule=$(uv run main.py)" >> $GITHUB_OUTPUT

      - name: Update workflow and push
        run: |
          sed -i "s/cron: \".*\"/cron: \"${{ steps.cron.outputs.schedule }}\"/" .github/workflows/schedule.yml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add .github/workflows/schedule.yml
            git commit -m "Update cron schedule"
            git push
          fi
